// apps/web/src/components/customer-account-statement-section.tsx
import { useEffect, useState } from "react";
import { getAccountStatement } from "../api/account-statement";
import type { AccountStatementEntry } from "../api/account-statement";
import { useAuth } from "../auth/use-auth";
import { formatBusinessDateTime } from "../lib/business-date";
import { formatMoney } from "../lib/money";
import { ErrorState } from "./error-state";

export interface CustomerAccountStatementSectionProps {
  customerId: string;
  /**
   * La ficha sube este contador cada vez que registra un cobro
   * (CustomerPaymentSection.onPaymentRegistered) para forzar una recarga:
   * un pago nuevo puede agregar una fila y mover closingBalance, y esta
   * sección no tiene otra forma de enterarse. Mismo mecanismo que
   * `reloadToken` de abajo, solo que ese lo dispara el propio botón
   * "Reintentar" de esta sección.
   */
  refreshSignal?: number;
}

const ENTRY_TYPE_LABELS: Record<AccountStatementEntry["type"], string> = {
  CHARGE: "Cargo",
  PAYMENT: "Abono",
};

type NonNullPaymentStatus = NonNullable<AccountStatementEntry["status"]>;

const PAYMENT_STATUS_LABELS: Record<NonNullPaymentStatus, string> = {
  PENDING: "Pendiente",
  CONFIRMED: "Confirmado",
  REJECTED: "Rechazado",
};

const PAYMENT_STATUS_BADGE_CLASS: Record<NonNullPaymentStatus, string> = {
  PENDING: "badge--warning",
  CONFIRMED: "badge--active",
  REJECTED: "badge--danger",
};

/**
 * Estado de cuenta (HU pendiente en backlog): cargos y abonos intercalados
 * de GET /customers/:id/account-statement, con el saldo corriente que ya
 * calcula el backend — no se recalcula acá. Mismo patrón que
 * CustomerPricesSection/CustomerPaymentSection: sección propia dentro de la
 * ficha, con su propio módulo de API.
 *
 * `openingBalance` del DTO NUNCA se muestra, a propósito: esta sección no
 * manda `from`, así que CustomersService.getAccountStatement lo deja fijo en
 * "0.00" para siempre (openingCaptured arranca en true cuando fromBoundary
 * es undefined) — no es "lo que el cliente debía antes de esta ventana", es
 * un cero que no representa historia real, y mostrárselo al dueño le diría
 * que cualquier cliente cargado del padrón arrancó en cero, lo cual es
 * falso. El arrastre real del padrón sigue visible como la fila con
 * isOpeningBalance en true dentro de `entries`. Si el día de mañana esta
 * pantalla ofrece un filtro `from`/`to`, openingBalance pasaría a
 * representar algo real y esta nota (y la razón para ignorarlo) quedaría
 * obsoleta — pero no lo agregues antes de eso.
 *
 * Una fila anulada se MUESTRA, marcada, en vez de esconderse: el cliente vio
 * esa entrega y va a preguntar por ella, y el dueño tiene que poder contarle
 * qué pasó. Su `runningBalance` ya viene sin el efecto de la fila, calculado
 * por la API: acá no se recalcula ni se marca el saldo. El DTO no trae el
 * motivo de la anulación, solo `voidedAt`, y con la fecha alcanza para decir
 * "esto se anotó y después se corrigió".
 */
export function CustomerAccountStatementSection({
  customerId,
  refreshSignal,
}: CustomerAccountStatementSectionProps) {
  const { apiClient } = useAuth();

  const [entries, setEntries] = useState<AccountStatementEntry[]>([]);
  const [closingBalance, setClosingBalance] = useState("0.00");
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [reloadToken, setReloadToken] = useState(0);

  useEffect(() => {
    let ignore = false;
    setIsLoading(true);
    setLoadError(null);

    getAccountStatement(apiClient, customerId)
      .then((statement) => {
        if (ignore) return;
        setEntries(statement.entries);
        setClosingBalance(statement.closingBalance);
      })
      .catch((error: unknown) => {
        if (!ignore) {
          setLoadError(
            error instanceof Error ? error.message : "No se pudo cargar el estado de cuenta.",
          );
        }
      })
      .finally(() => {
        if (!ignore) setIsLoading(false);
      });

    return () => {
      ignore = true;
    };
  }, [apiClient, customerId, reloadToken, refreshSignal]);

  return (
    <section className="card">
      <div className="card__body">
        <div className="page-header">
          <h2>Estado de cuenta</h2>
          {!isLoading && loadError === null && (
            <span className="stat__value">{formatMoney(closingBalance)}</span>
          )}
        </div>

        {loadError !== null ? (
          <ErrorState message={loadError} onRetry={() => setReloadToken((token) => token + 1)} />
        ) : isLoading ? (
          <p className="state" role="status">
            Cargando estado de cuenta…
          </p>
        ) : entries.length === 0 ? (
          <p className="state">Sin movimientos todavía.</p>
        ) : (
          <div className="table-scroll">
            <table className="table">
              <caption className="visually-hidden">Estado de cuenta del cliente</caption>
              <thead>
                <tr>
                  <th scope="col">Fecha</th>
                  <th scope="col">Tipo</th>
                  <th scope="col" className="table__numeric">
                    Monto
                  </th>
                  <th scope="col" className="table__numeric">
                    Saldo
                  </th>
                  <th scope="col">Detalle</th>
                </tr>
              </thead>
              <tbody>
                {entries.map((entry) => (
                  <tr key={entry.saleId ?? entry.paymentId ?? entry.date}>
                    <td>{formatBusinessDateTime(entry.date)}</td>
                    <td>
                      {ENTRY_TYPE_LABELS[entry.type]}
                      {entry.isOpeningBalance && (
                        <>
                          {" "}
                          <span className="badge badge--muted">Saldo inicial</span>
                        </>
                      )}
                      {/* "Anulado", no "Anulada": el badge queda pegado a
                          "Cargo" o "Abono" —los dos masculinos—, y el mismo
                          concepto en la bandeja de pagos ya dice "Anulado". */}
                      {entry.voidedAt !== null && (
                        <>
                          {" "}
                          <span className="badge badge--danger">Anulado</span>
                        </>
                      )}
                    </td>
                    {/* El tachado refuerza al badge, nunca lo reemplaza. */}
                    <td
                      className={
                        entry.voidedAt !== null ? "table__numeric money--voided" : "table__numeric"
                      }
                    >
                      {formatMoney(entry.amount)}
                    </td>
                    <td className="table__numeric">{formatMoney(entry.runningBalance)}</td>
                    <td>
                      {entry.type === "PAYMENT" ? (
                        <>
                          {entry.paymentMethodName}
                          {entry.status !== null && (
                            <>
                              {" "}
                              <span className={`badge ${PAYMENT_STATUS_BADGE_CLASS[entry.status]}`}>
                                {PAYMENT_STATUS_LABELS[entry.status]}
                              </span>
                            </>
                          )}
                        </>
                      ) : (
                        entry.locationName !== null && (
                          <span className="cell-secondary">{entry.locationName}</span>
                        )
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}

// apps/web-nuxt/app/components/CustomerAccountStatementSection.vue
<script setup lang="ts">
import { formatInstantInLima, formatSoles } from "@yacco/shared";
import type { AccountStatement, AccountStatementEntry, PaymentStatus } from "@yacco/shared";

/**
 * Estado de cuenta: cargos y abonos intercalados, con el saldo corriente que
 * calcula la API (acá no se recalcula nada).
 *
 * `openingBalance` NO se muestra: sin `from`, la API lo deja fijo en "0.00", y
 * mostrarlo le diría al dueño que todo cliente del padrón arrancó en cero. El
 * arrastre real es la fila marcada «Saldo inicial».
 *
 * Una fila anulada se MUESTRA marcada, no se esconde: el cliente vio esa
 * entrega y va a preguntar. Su saldo corriente ya viene sin su efecto.
 */
const props = defineProps<{
  customerId: string;
  /** La ficha lo sube tras registrar un cobro, que agrega una fila y mueve el saldo. */
  refreshSignal: number;
}>();

const api = useApi();
const statement = ref<AccountStatement | null>(null);
const loading = ref(true);
const loadError = ref<string | null>(null);

async function load(): Promise<void> {
  loading.value = true;
  loadError.value = null;
  try {
    statement.value = await api.request<AccountStatement>(
      `/customers/${props.customerId}/account-statement`,
    );
  } catch (error) {
    loadError.value = describeApiFailure(error);
  } finally {
    loading.value = false;
  }
}
onMounted(load);
watch(() => props.refreshSignal, load);

const STATUS: Record<PaymentStatus, { label: string; color: "warning" | "success" | "error" }> = {
  PENDING: { label: "Pendiente", color: "warning" },
  CONFIRMED: { label: "Confirmado", color: "success" },
  REJECTED: { label: "Rechazado", color: "error" },
};

const entries = computed(() => statement.value?.entries ?? []);

function rowKey(entry: AccountStatementEntry): string {
  return entry.saleId ?? entry.paymentId ?? entry.date;
}
</script>

<template>
  <SectionCard title="Estado de cuenta" description="Cargos y abonos, del más antiguo al último.">
    <template v-if="!loading && !loadError && statement" #actions>
      <span class="text-sm text-muted">Saldo</span>
      <span class="text-lg font-semibold text-highlighted tabular-nums">{{
        formatSoles(statement.closingBalance)
      }}</span>
    </template>

    <ListStatus
      v-if="loadError || loading || entries.length === 0"
      :error-message="loadError"
      :loading="loading"
      :empty="true"
      loading-label="Cargando estado de cuenta…"
      error-title="No se pudo cargar el estado de cuenta"
      empty-icon="i-lucide-receipt"
      empty-title="Sin movimientos todavía"
      empty-description="Las ventas y los cobros de este cliente van a aparecer acá."
      @retry="load"
    />

    <div v-else class="overflow-x-auto">
      <table class="w-full text-sm">
        <caption class="sr-only">
          Estado de cuenta del cliente
        </caption>
        <thead class="text-left text-xs tracking-wide text-muted uppercase">
          <tr>
            <th scope="col" class="py-2 font-medium">Fecha</th>
            <th scope="col" class="py-2 font-medium">Tipo</th>
            <th scope="col" class="py-2 text-right font-medium">Monto</th>
            <th scope="col" class="py-2 text-right font-medium">Saldo</th>
            <th scope="col" class="py-2 pl-4 font-medium">Detalle</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-default">
          <tr
            v-for="entry in entries"
            :key="rowKey(entry)"
            :class="entry.voidedAt === null ? undefined : 'bg-elevated/60'"
          >
            <td class="py-3 whitespace-nowrap text-muted tabular-nums">
              {{ formatInstantInLima(entry.date) }}
            </td>
            <td class="py-3">
              <span class="flex flex-wrap items-center gap-1.5">
                {{ entry.type === "CHARGE" ? "Cargo" : "Abono" }}
                <UBadge
                  v-if="entry.isOpeningBalance"
                  color="neutral"
                  variant="soft"
                  size="sm"
                  label="Saldo inicial"
                />
                <!-- "Anulado": va pegado a Cargo o Abono, los dos masculinos. -->
                <UBadge
                  v-if="entry.voidedAt !== null"
                  color="error"
                  variant="subtle"
                  size="sm"
                  label="Anulado"
                />
              </span>
            </td>
            <!-- El tachado refuerza al badge, nunca lo reemplaza. -->
            <td
              class="py-3 text-right tabular-nums"
              :class="entry.voidedAt === null ? undefined : 'text-muted line-through'"
            >
              {{ formatSoles(entry.amount) }}
            </td>
            <td class="py-3 text-right font-medium tabular-nums">
              {{ formatSoles(entry.runningBalance) }}
            </td>
            <td class="py-3 pl-4">
              <span v-if="entry.type === 'PAYMENT'" class="flex flex-wrap items-center gap-1.5">
                {{ entry.paymentMethodName }}
                <UBadge
                  v-if="entry.status !== null"
                  :color="STATUS[entry.status].color"
                  variant="subtle"
                  size="sm"
                  :label="STATUS[entry.status].label"
                />
              </span>
              <span v-else-if="entry.locationName !== null" class="text-muted">{{
                entry.locationName
              }}</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </SectionCard>
</template>
