// apps/web/src/components/customer-prices-section.tsx
import { Fragment, useEffect, useState } from "react";
import type { FormEvent } from "react";
import {
  createCustomerPrice,
  deleteCustomerPrice,
  listCustomerPrices,
  listEffectivePrices,
  updateCustomerPrice,
} from "../api/customer-prices";
import type { CustomerPrice, EffectivePrice } from "../api/customer-prices";
import { listProducts } from "../api/products";
import type { Product } from "../api/products";
import { useAuth } from "../auth/use-auth";
import { formatMoney, isValidMoney } from "../lib/money";
import { ErrorState } from "./error-state";

export interface CustomerPricesSectionProps {
  customerId: string;
  /** Management (create/edit/delete) is ADMIN-only — the backend enforces
   * this; hiding the controls here is only UI clarity, not the security
   * boundary. A non-ADMIN reads `effective-prices` instead of the
   * management list below, since the API refuses the latter to a SELLER. */
  isAdmin: boolean;
}

/** ADMIN view: only the agreed (customer-wide) prices, with full CRUD. */
export function CustomerPricesSection({ customerId, isAdmin }: CustomerPricesSectionProps) {
  const { apiClient } = useAuth();

  const [products, setProducts] = useState<Product[]>([]);
  const [prices, setPrices] = useState<CustomerPrice[]>([]);
  const [effectivePrices, setEffectivePrices] = useState<EffectivePrice[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [reloadToken, setReloadToken] = useState(0);

  const [isAddingPrice, setIsAddingPrice] = useState(false);
  const [newProductId, setNewProductId] = useState("");
  const [newPrice, setNewPrice] = useState("");
  const [createError, setCreateError] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);

  const [editingId, setEditingId] = useState<string | null>(null);
  const [editPrice, setEditPrice] = useState("");
  const [confirmingDeleteId, setConfirmingDeleteId] = useState<string | null>(null);
  /**
   * El error de una acción de fila lleva el id del precio, no solo el texto:
   * se muestra pegado a la fila que se estaba editando en vez de una sola vez
   * arriba de la sección. Con dos precios daba igual; con la lista entera de
   * productos de un cliente, un mensaje arriba no dice cuál falló.
   */
  const [actionError, setActionError] = useState<{ priceId: string; message: string } | null>(null);
  const [isSavingAction, setIsSavingAction] = useState(false);

  useEffect(() => {
    let ignore = false;
    setIsLoading(true);
    setLoadError(null);

    const handleError = (error: unknown) => {
      if (ignore) return;
      setLoadError(error instanceof Error ? error.message : "No se pudieron cargar los precios.");
    };
    const handleDone = () => {
      if (!ignore) setIsLoading(false);
    };

    if (isAdmin) {
      Promise.all([listProducts(apiClient), listCustomerPrices(apiClient, customerId)])
        .then(([productList, priceList]) => {
          if (ignore) return;
          setProducts(productList);
          setPrices(priceList);
        })
        .catch(handleError)
        .finally(handleDone);
    } else {
      listEffectivePrices(apiClient, customerId)
        .then((priceList) => {
          if (!ignore) setEffectivePrices(priceList);
        })
        .catch(handleError)
        .finally(handleDone);
    }

    return () => {
      ignore = true;
    };
  }, [apiClient, customerId, isAdmin, reloadToken]);

  const selectedNewProduct = products.find((product) => product.id === newProductId) ?? null;

  function handleStartAdd() {
    setIsAddingPrice(true);
    setNewProductId("");
    setNewPrice("");
    setCreateError(null);
  }

  function handleCancelAdd() {
    setIsAddingPrice(false);
  }

  function handleCreate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (isCreating) return;
    if (newProductId === "") {
      setCreateError("Elige un producto");
      return;
    }
    if (!isValidMoney(newPrice.trim())) {
      setCreateError('El precio debe ser un monto válido, como "12.50"');
      return;
    }

    setIsCreating(true);
    setCreateError(null);
    createCustomerPrice(apiClient, customerId, { productId: newProductId, price: newPrice.trim() })
      .then((created) => {
        setPrices((current) => [...current, created]);
        setIsAddingPrice(false);
      })
      .catch((error: unknown) => {
        // The backend's message names the concrete product ("ya existe un
        // precio para..."); shown verbatim so it never drifts from the
        // message the API actually maintains.
        setCreateError(error instanceof Error ? error.message : "No se pudo pactar el precio.");
      })
      .finally(() => setIsCreating(false));
  }

  function handleStartEdit(price: CustomerPrice) {
    setEditingId(price.id);
    setEditPrice(price.price);
    setActionError(null);
  }

  function handleCancelEdit() {
    setEditingId(null);
  }

  function handleSaveEdit(priceId: string) {
    if (isSavingAction) return;
    if (!isValidMoney(editPrice.trim())) {
      setActionError({
        priceId,
        message: 'El precio debe ser un monto válido, como "12.50"',
      });
      return;
    }

    setIsSavingAction(true);
    setActionError(null);
    updateCustomerPrice(apiClient, customerId, priceId, { price: editPrice.trim() })
      .then((updated) => {
        setPrices((current) => current.map((price) => (price.id === priceId ? updated : price)));
        setEditingId(null);
      })
      .catch((error: unknown) => {
        setActionError({
          priceId,
          message: error instanceof Error ? error.message : "No se pudo actualizar el precio.",
        });
      })
      .finally(() => setIsSavingAction(false));
  }

  function handleStartDelete(priceId: string) {
    setConfirmingDeleteId(priceId);
    setActionError(null);
  }

  function handleCancelDelete() {
    setConfirmingDeleteId(null);
  }

  function handleConfirmDelete(priceId: string) {
    if (isSavingAction) return;
    setIsSavingAction(true);
    setActionError(null);
    deleteCustomerPrice(apiClient, customerId, priceId)
      .then(() => {
        setPrices((current) => current.filter((price) => price.id !== priceId));
        setConfirmingDeleteId(null);
      })
      .catch((error: unknown) => {
        setActionError({
          priceId,
          message: error instanceof Error ? error.message : "No se pudo eliminar el precio.",
        });
      })
      .finally(() => setIsSavingAction(false));
  }

  return (
    <section className="card">
      <div className="card__body">
        <div className="page-header">
          <h2>Precios pactados</h2>
          {isAdmin && !isAddingPrice && (
            <button
              type="button"
              className="button button--secondary"
              onClick={handleStartAdd}
              disabled={isLoading}
            >
              Agregar precio
            </button>
          )}
        </div>

        {loadError ? (
          <ErrorState message={loadError} onRetry={() => setReloadToken((token) => token + 1)} />
        ) : isLoading ? (
          <p className="state" role="status">
            Cargando precios…
          </p>
        ) : isAdmin ? (
          <>
            {createError && (
              <div className="notice notice--error" role="alert">
                {createError}
              </div>
            )}

            {isAddingPrice && (
              <form className="form-grid" onSubmit={handleCreate} noValidate>
                <div className="field">
                  <label className="field__label" htmlFor="newPriceProduct">
                    Producto
                  </label>
                  <select
                    id="newPriceProduct"
                    value={newProductId}
                    disabled={isCreating}
                    onChange={(event) => setNewProductId(event.target.value)}
                  >
                    <option value="">Selecciona un producto</option>
                    {products.map((product) => (
                      <option key={product.id} value={product.id}>
                        {product.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="field">
                  <label className="field__label" htmlFor="newPriceValue">
                    Precio pactado
                  </label>
                  <input
                    id="newPriceValue"
                    type="text"
                    inputMode="decimal"
                    placeholder="12.50"
                    value={newPrice}
                    disabled={isCreating}
                    onChange={(event) => setNewPrice(event.target.value)}
                  />
                  {selectedNewProduct && (
                    <span className="field__hint">
                      Precio de lista: {formatMoney(selectedNewProduct.listPrice)}
                    </span>
                  )}
                </div>
                <div className="form-actions form-grid__full">
                  <button
                    type="button"
                    className="button button--secondary"
                    onClick={handleCancelAdd}
                    disabled={isCreating}
                  >
                    Cancelar
                  </button>
                  <button type="submit" className="button button--primary" disabled={isCreating}>
                    {isCreating ? "Guardando…" : "Guardar precio"}
                  </button>
                </div>
              </form>
            )}

            {prices.length === 0 ? (
              <p className="state">
                Este cliente no tiene precios pactados: rige el precio de lista para todos sus
                productos.
              </p>
            ) : (
              <div className="table-scroll">
                <table className="table">
                  <caption className="visually-hidden">Precios pactados del cliente</caption>
                  <thead>
                    <tr>
                      <th scope="col">Producto</th>
                      <th scope="col" className="table__numeric">
                        Precio
                      </th>
                      <th scope="col" className="table__actions">
                        <span className="visually-hidden">Acciones</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {prices.map((price) => (
                      <Fragment key={price.id}>
                        <tr>
                          <td>{price.product.name}</td>
                          <td className="table__numeric">
                            {editingId === price.id ? (
                              <input
                                aria-label={`Precio de ${price.product.name}`}
                                type="text"
                                inputMode="decimal"
                                value={editPrice}
                                disabled={isSavingAction}
                                onChange={(event) => setEditPrice(event.target.value)}
                              />
                            ) : (
                              formatMoney(price.price)
                            )}
                          </td>
                          <td className="table__actions">
                            {confirmingDeleteId === price.id ? (
                              <span>
                                ¿Eliminar? Volverá a regir el precio de lista.{" "}
                                <button
                                  type="button"
                                  className="button button--secondary"
                                  onClick={handleCancelDelete}
                                  disabled={isSavingAction}
                                >
                                  No
                                </button>{" "}
                                <button
                                  type="button"
                                  className="button button--primary"
                                  onClick={() => handleConfirmDelete(price.id)}
                                  disabled={isSavingAction}
                                >
                                  {isSavingAction ? "Eliminando…" : "Sí, eliminar"}
                                </button>
                              </span>
                            ) : editingId === price.id ? (
                              <>
                                <button
                                  type="button"
                                  className="button button--secondary"
                                  onClick={handleCancelEdit}
                                  disabled={isSavingAction}
                                >
                                  Cancelar
                                </button>{" "}
                                <button
                                  type="button"
                                  className="button button--primary"
                                  onClick={() => handleSaveEdit(price.id)}
                                  disabled={isSavingAction}
                                >
                                  {isSavingAction ? "Guardando…" : "Guardar"}
                                </button>
                              </>
                            ) : (
                              <>
                                <button
                                  type="button"
                                  className="button button--ghost"
                                  onClick={() => handleStartEdit(price)}
                                >
                                  Editar
                                </button>{" "}
                                <button
                                  type="button"
                                  className="button button--ghost"
                                  onClick={() => handleStartDelete(price.id)}
                                >
                                  Eliminar
                                </button>
                              </>
                            )}
                          </td>
                        </tr>
                        {/* Fila aparte y no dentro de la celda de acciones: esa
                          columna es angosta y un mensaje ahí desborda la
                          tabla. Acá queda pegado a su fila y con ancho para
                          leerse entero. */}
                        {actionError?.priceId === price.id && (
                          <tr>
                            <td colSpan={3}>
                              <p className="notice notice--error" role="alert">
                                {actionError.message}
                              </p>
                            </td>
                          </tr>
                        )}
                      </Fragment>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        ) : (
          <div className="table-scroll">
            <table className="table">
              <caption className="visually-hidden">Precios efectivos del cliente</caption>
              <thead>
                <tr>
                  <th scope="col">Producto</th>
                  <th scope="col" className="table__numeric">
                    Precio
                  </th>
                  <th scope="col">Origen</th>
                </tr>
              </thead>
              <tbody>
                {effectivePrices.map((item) => (
                  <tr key={item.product.id}>
                    <td>{item.product.name}</td>
                    <td className="table__numeric">{formatMoney(item.price)}</td>
                    <td>
                      {item.source === "LIST" ? (
                        <span className="cell-secondary">Precio de lista</span>
                      ) : (
                        <span className="badge badge--info">Pactado</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}

// apps/web-nuxt/app/components/CustomerPricesSection.vue
<script setup lang="ts">
import { formatSoles, isMoneyInput } from "@yacco/shared";
import type { CustomerPrice, EffectivePrice, Product } from "@yacco/shared";

/**
 * Precios pactados del cliente.
 *
 * ADMIN gestiona (alta, edición, baja) la lista de pactados. Cualquier otro
 * rol lee los precios EFECTIVOS, de sólo lectura: la API le niega la lista de
 * gestión a un vendedor. Esconder los controles acá es claridad; la barrera de
 * seguridad está en la API.
 */
const props = defineProps<{ customerId: string; isAdmin: boolean }>();

const api = useApi();
const base = computed(() => `/customers/${props.customerId}`);
const PRICE_FORMAT_ERROR = 'El precio debe ser un monto válido, como "12.50"';

const products = ref<Product[]>([]);
const prices = ref<CustomerPrice[]>([]);
const effective = ref<EffectivePrice[]>([]);
const loading = ref(true);
const loadError = ref<string | null>(null);

async function load(): Promise<void> {
  loading.value = true;
  loadError.value = null;
  try {
    if (props.isAdmin) {
      const [productList, priceList] = await Promise.all([
        api.request<Product[]>("/products"),
        api.request<CustomerPrice[]>(`${base.value}/prices`),
      ]);
      products.value = productList;
      prices.value = priceList;
    } else {
      effective.value = await api.request<EffectivePrice[]>(`${base.value}/effective-prices`);
    }
  } catch (error) {
    loadError.value = describeApiFailure(error);
  } finally {
    loading.value = false;
  }
}
onMounted(load);

// Alta. No se prellena con el precio de lista: un pactado es una decisión, y
// dejar el de lista escrito invita a guardarlo sin mirarlo.
const adding = ref(false);
const newProductId = ref<string | undefined>(undefined);
const newPrice = ref("");
const createError = ref<string | null>(null);
const creating = ref(false);
const productItems = computed(() =>
  products.value.map((product) => ({ label: product.name, value: product.id })),
);
const chosenProduct = computed(() =>
  products.value.find((product) => product.id === newProductId.value),
);

function startAdd(): void {
  adding.value = true;
  newProductId.value = undefined;
  newPrice.value = "";
  createError.value = null;
}

async function create(): Promise<void> {
  if (creating.value) return;
  if (newProductId.value === undefined) {
    createError.value = "Elige un producto";
    return;
  }
  const price = newPrice.value.trim();
  if (!isMoneyInput(price)) {
    createError.value = PRICE_FORMAT_ERROR;
    return;
  }
  creating.value = true;
  createError.value = null;
  try {
    const created = await api.request<CustomerPrice>(`${base.value}/prices`, {
      method: "POST",
      body: { productId: newProductId.value, price },
    });
    prices.value = [...prices.value, created];
    adding.value = false;
  } catch (error) {
    // El mensaje de la API nombra el producto ("ya existe un precio para…").
    createError.value = describeApiFailure(error);
  } finally {
    creating.value = false;
  }
}

// Acciones de fila. El error lleva el id del precio: se muestra pegado a la
// fila que falló, no arriba, donde con muchos productos no dice cuál fue.
const editingId = ref<string | null>(null);
const editPrice = ref("");
const deletingId = ref<string | null>(null);
const rowError = ref<{ priceId: string; message: string } | null>(null);
const saving = ref(false);

function startEdit(price: CustomerPrice): void {
  editingId.value = price.id;
  editPrice.value = price.price;
  deletingId.value = null;
  rowError.value = null;
}

async function saveEdit(priceId: string): Promise<void> {
  if (saving.value) return;
  const price = editPrice.value.trim();
  if (!isMoneyInput(price)) {
    rowError.value = { priceId, message: PRICE_FORMAT_ERROR };
    return;
  }
  saving.value = true;
  rowError.value = null;
  try {
    const updated = await api.request<CustomerPrice>(`${base.value}/prices/${priceId}`, {
      method: "PATCH",
      body: { price },
    });
    prices.value = prices.value.map((item) => (item.id === priceId ? updated : item));
    editingId.value = null;
  } catch (error) {
    rowError.value = { priceId, message: describeApiFailure(error) };
  } finally {
    saving.value = false;
  }
}

function startDelete(priceId: string): void {
  deletingId.value = priceId;
  editingId.value = null;
  rowError.value = null;
}

async function confirmDelete(priceId: string): Promise<void> {
  if (saving.value) return;
  saving.value = true;
  rowError.value = null;
  try {
    await api.request<void>(`${base.value}/prices/${priceId}`, { method: "DELETE" });
    prices.value = prices.value.filter((item) => item.id !== priceId);
    deletingId.value = null;
  } catch (error) {
    rowError.value = { priceId, message: describeApiFailure(error) };
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <SectionCard
    title="Precios pactados"
    description="Lo que paga este cliente cuando no rige el precio de lista."
  >
    <template v-if="isAdmin && !adding" #actions>
      <UButton
        color="neutral"
        variant="outline"
        icon="i-lucide-plus"
        label="Agregar precio"
        :disabled="loading"
        @click="startAdd"
      />
    </template>

    <ListStatus
      v-if="loadError || loading"
      :error-message="loadError"
      :loading="loading"
      :empty="false"
      loading-label="Cargando precios…"
      error-title="No se pudieron cargar los precios"
      empty-title=""
      empty-description=""
      @retry="load"
    />

    <div v-else-if="isAdmin" class="space-y-4">
      <UAlert v-if="createError" role="alert" color="error" variant="subtle" :title="createError" />

      <form
        v-if="adding"
        class="grid gap-4 rounded-md bg-elevated p-4 sm:grid-cols-[1fr_12rem] sm:items-start"
        novalidate
        @submit.prevent="create"
      >
        <UFormField label="Producto" name="newPriceProduct">
          <USelect
            v-model="newProductId"
            :items="productItems"
            placeholder="Selecciona un producto"
            :disabled="creating"
            class="w-full"
          />
        </UFormField>
        <UFormField
          label="Precio pactado"
          name="newPriceValue"
          :help="
            chosenProduct ? `Precio de lista: ${formatSoles(chosenProduct.listPrice)}` : undefined
          "
        >
          <UInput
            v-model="newPrice"
            inputmode="decimal"
            placeholder="12.50"
            :disabled="creating"
            class="w-full"
          />
        </UFormField>
        <div class="flex justify-end gap-2 sm:col-span-2">
          <UButton
            color="neutral"
            variant="ghost"
            label="Cancelar"
            :disabled="creating"
            @click="adding = false"
          />
          <UButton
            type="submit"
            :disabled="creating"
            :label="creating ? 'Guardando…' : 'Guardar precio'"
          />
        </div>
      </form>

      <p v-if="prices.length === 0" class="py-6 text-center text-muted">
        Este cliente no tiene precios pactados: rige el precio de lista para todos sus productos.
      </p>

      <table v-else class="w-full text-sm">
        <caption class="sr-only">
          Precios pactados del cliente
        </caption>
        <thead class="text-left text-xs tracking-wide text-muted uppercase">
          <tr>
            <th scope="col" class="py-2 font-medium">Producto</th>
            <th scope="col" class="py-2 text-right font-medium">Precio</th>
            <th scope="col" class="py-2"><span class="sr-only">Acciones</span></th>
          </tr>
        </thead>
        <tbody class="divide-y divide-default">
          <template v-for="price in prices" :key="price.id">
            <tr>
              <td class="py-3 font-medium text-highlighted">{{ price.product.name }}</td>
              <td class="py-3 text-right tabular-nums">
                <UInput
                  v-if="editingId === price.id"
                  v-model="editPrice"
                  :aria-label="`Precio de ${price.product.name}`"
                  inputmode="decimal"
                  :disabled="saving"
                  class="ml-auto w-32"
                />
                <template v-else>{{ formatSoles(price.price) }}</template>
              </td>
              <td class="py-3 text-right">
                <div
                  v-if="deletingId === price.id"
                  class="flex flex-wrap items-center justify-end gap-2"
                >
                  <span class="text-muted">¿Eliminar? Volverá a regir el precio de lista.</span>
                  <UButton
                    color="neutral"
                    variant="outline"
                    size="sm"
                    label="No"
                    :disabled="saving"
                    @click="deletingId = null"
                  />
                  <UButton
                    color="error"
                    size="sm"
                    :disabled="saving"
                    :label="saving ? 'Eliminando…' : 'Sí, eliminar'"
                    @click="confirmDelete(price.id)"
                  />
                </div>
                <div v-else-if="editingId === price.id" class="flex justify-end gap-2">
                  <UButton
                    color="neutral"
                    variant="outline"
                    size="sm"
                    label="Cancelar"
                    :disabled="saving"
                    @click="editingId = null"
                  />
                  <UButton
                    size="sm"
                    :disabled="saving"
                    :label="saving ? 'Guardando…' : 'Guardar'"
                    @click="saveEdit(price.id)"
                  />
                </div>
                <div v-else class="flex justify-end gap-1">
                  <UButton
                    color="neutral"
                    variant="ghost"
                    size="sm"
                    label="Editar"
                    :aria-label="`Editar precio de ${price.product.name}`"
                    @click="startEdit(price)"
                  />
                  <UButton
                    color="neutral"
                    variant="ghost"
                    size="sm"
                    label="Eliminar"
                    :aria-label="`Eliminar precio de ${price.product.name}`"
                    @click="startDelete(price.id)"
                  />
                </div>
              </td>
            </tr>
            <tr v-if="rowError?.priceId === price.id">
              <td colspan="3" class="pb-3">
                <UAlert role="alert" color="error" variant="subtle" :title="rowError.message" />
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>

    <table v-else class="w-full text-sm">
      <caption class="sr-only">
        Precios efectivos del cliente
      </caption>
      <thead class="text-left text-xs tracking-wide text-muted uppercase">
        <tr>
          <th scope="col" class="py-2 font-medium">Producto</th>
          <th scope="col" class="py-2 text-right font-medium">Precio</th>
          <th scope="col" class="py-2 pl-4 font-medium">Origen</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-default">
        <tr v-for="item in effective" :key="item.product.id">
          <td class="py-3 font-medium text-highlighted">{{ item.product.name }}</td>
          <td class="py-3 text-right tabular-nums">{{ formatSoles(item.price) }}</td>
          <td class="py-3 pl-4">
            <span v-if="item.source === 'LIST'" class="text-muted">Precio de lista</span>
            <UBadge v-else color="info" variant="subtle" label="Pactado" />
          </td>
        </tr>
      </tbody>
    </table>
  </SectionCard>
</template>
